# Generated by Django 5.2.6 on 2025-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_fabrication',
            field=models.DateField(auto_now=True),
        ),
    ]
